<table align="left" width=100%>
    <tr>
        <td width="10%">
            <img src="in_class.png">
        </td>
        <td>
            <div align="center">
                <font color="#21618C" size=8px>
                  <b> Inclass - Lab <br> (Day 1) </b>
                </font>
            </div>
        </td>
    </tr>
</table>

##  Table of Content

1. **[One Dimensional Array](#1D)**
2. **[Two Dimensional Array](#2D)**
3. **[Stacking](#Stacking)**
4. **[Splitting](#Splitting)**
5. **[For Loop](#loop)**

**Import the NumPy library before solving the exercises**

### Let's begin with some hands-on practice exercises

<a id="1D"> </a>
## 1. One Dimensional Array

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>1. Write a NumPy program to convert a list of numeric values into a one-dimensional NumPy array</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the list given below: (or create your own list)**<br>

    list_temperature = [3.04, 1.65, 5.76, 1.66, 1.54, 4.69, 2.68]

In [7]:
list_temperature = [3.04, 1.65, 5.76, 1.66, 1.54, 4.69, 2.68]
np.array([list_temperature])

array([[3.04, 1.65, 5.76, 1.66, 1.54, 4.69, 2.68]])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>2. Create a 1D array of weights of 10 students and retrieve all the weights greater than 68</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the weights given below: (or create your own list)**

    weights = [74.2, 85, 74, 67.9, 52, 70.5, 86, 51.8, 64, 82]

In [14]:
weights = [74.2, 85, 74, 67.9, 52, 70.5, 86, 51.8, 64, 82]
x = np.array(weights)
x>68
x[x>68]

array([74.2, 85. , 74. , 70.5, 86. , 82. ])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>3. Write a code to generate 10 random integers between 20 to 40 (Is it possible to generate same random numbers everytime? If yes, describe the function)
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [26]:
np.random.seed(100)
np.random.randint(20,41,10)


array([28, 23, 27, 35, 36, 30, 40, 22, 22, 22])

In [27]:
# We can generate the same random numbers everytime by using 'np.random.seed()'


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>4. Write a program to get the fifth power of the first five positive integers
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [56]:
x =np.array([1,2,3,4,5])
x1 = x**5
x1

array([   1,   32,  243, 1024, 3125], dtype=int32)

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>5. Write a program to create an array of all the odd integers from 50 to 100 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [62]:
x = np.arange(51,101,2)a
x

array([51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83,
       85, 87, 89, 91, 93, 95, 97, 99])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>6. Write a program to calculate the sum of each column </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below: (or create your own array)**

    A = [[1, 4, 8], [5, 7, 3], [9, 14, 2]]

In [68]:
A = [[1, 4, 8], [5, 7, 3], [9, 14, 2]]
a = np.array(A)

In [70]:
a_sum = sum(a)

In [71]:
a_sum

array([15, 25, 13])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>7. Write a code to get the element-wise remainder of an array after division by 8 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the list given below:**<br>
    
    num = [42, 87, 90, 14, 32, 75, 61, 80, 92]

In [73]:
num = [42, 87, 90, 14, 32, 75, 61, 80, 92]
n = np.array(num)

In [74]:
n

array([42, 87, 90, 14, 32, 75, 61, 80, 92])

In [76]:
n_div = n % 8

In [77]:
n_div

array([2, 7, 2, 6, 0, 3, 5, 0, 4], dtype=int32)

<a id="2D"> </a>
## 2. Two Dimensional Array

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>8. Create a 2D numpy array from a 1D array of 20 elements of your choice. Further, subset the first 5 elements from the second element of a resulting 2D array 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [82]:
# type your code here
#Create a 2D numpy array from a 1D array of 20 elements of your choice.
# Reshape the 1D array as a matrix with 5 columns(ie 4x5 matrix)
# access the first row of the matrix 

x = np.random.randint(0,100,20)
x

array([38, 44, 18, 64, 56, 34, 53, 74, 17, 72, 13, 30, 17, 53, 68, 50, 91,
       91, 83, 53])

In [84]:
n = np.reshape(x,(4,5))
n

array([[38, 44, 18, 64, 56],
       [34, 53, 74, 17, 72],
       [13, 30, 17, 53, 68],
       [50, 91, 91, 83, 53]])

In [101]:
a = n[0:1,0:5]

In [102]:
a

array([[38, 44, 18, 64, 56]])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>9. Write a program to find common values between two arrays 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the lists given below:**<br>

    prices_monday = [10, 30, 50, 60, 90]

    prices_tuesday = [50, 20, 80, 125, 10, 70]

In [1]:
# type your code here

prices_monday = [10, 30, 50, 60, 90]

prices_tuesday = [50, 20, 80, 125, 10, 70]

import numpy as np
np.intersect1d(prices_monday,prices_tuesday)

array([10, 50])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>10. Write a program to find BMI of the patients whose height and weight is provided in the list given below 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the lists given below:**<br>

    list of weights (in kg)
    weights = [57, 69, 54, 65 ,71, 62, 56]

    list of heights (in m)<br>
    heights = [1.59, 1.75, 1.66, 1.74, 1.64, 1.72, 1.53] 

In [103]:
# type your code here
# bmi = w/h**2


weights = [57, 69, 54, 65 ,71, 62, 56]
heights = [1.59, 1.75, 1.66, 1.74, 1.64, 1.72, 1.53] 


In [106]:
import numpy as np

w = np.array(weights)
h = np.array(heights)

In [109]:
w

array([57, 69, 54, 65, 71, 62, 56])

In [110]:
h

array([1.59, 1.75, 1.66, 1.74, 1.64, 1.72, 1.53])

In [111]:
bmi = w/h**2

In [112]:
bmi

array([22.54657648, 22.53061224, 19.59645812, 21.46915048, 26.39797739,
       20.9572742 , 23.922423  ])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>11. Write a program to add a new row ([5,7]) at the last position in the array given below 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**

    array1 = [[3, 4], [8, 2],[5, 9]]

In [124]:
ini_array = [[3, 4], [8, 2],[5, 9]]
new_array = ([5,7])
#use vstack or concatenate 

In [126]:
np.row_stack((ini_array,new_array))

array([[3, 4],
       [8, 2],
       [5, 9],
       [5, 7]])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>12. Write a code to print the identity matrix of order 5</b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [129]:
# type your code here
 
i = np.identity(5)
i

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>13. Write a program to transpose a matrix 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the matrix given below:**
    
    M = [[15, 17, 45, 56], [7, 42, 15, 63], [54, 3, 61, 41], [0, 87, 16, 20]]

In [132]:
# type your code here
#np.transpose 
M = [[15, 17, 45, 56], [7, 42, 15, 63], [54, 3, 61, 41], [0, 87, 16, 20]]

m1 = np.transpose(M)
m1

array([[15,  7, 54,  0],
       [17, 42,  3, 87],
       [45, 15, 61, 16],
       [56, 63, 41, 20]])

<a id="Stacking"> </a>
## 3. Stacking

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>14. Write a program to combine the two arrays vertically</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the arrays given below: (or create your own array)**<br>

    A1 = [[5, 9], [7, 6]]

    A2 = [[8,-7], [0,4]]

Combine the array A2 with A1

In [3]:

# type your code here
#use vstack 

#out put = [5 9
#           7 6
#           8-7
#           0 4]
                
import numpy as np

A1 = [[5, 9], [7, 6]]

A2 = [[8,-7], [0,4]]

In [4]:
A1

[[5, 9], [7, 6]]

In [5]:
A2

[[8, -7], [0, 4]]

In [134]:
A3 = np.vstack((A1,A2))
A3

array([[ 5,  9],
       [ 7,  6],
       [ 8, -7],
       [ 0,  4]])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>15. Write a code to combine the two arrays horizontally</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the arrays given below: (or create your own array)**

    A1 = [[-81, 75, 40], [27, 67, 52]]

    A2 = [[15, 54], [39, 56]]

Combine the array A2 with A1

In [135]:
# type your code here

A1 = [[-81, 75, 40], [27, 67, 52]]

A2 = [[15, 54], [39, 56]]

In [136]:
A3 = np.hstack((A1,A2))

In [137]:
A3

array([[-81,  75,  40,  15,  54],
       [ 27,  67,  52,  39,  56]])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>16. Write a code to divide the array into three sub-arrays containing
                       equal number of rows</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**<br>

    A = [[4, 7], [2, -3], [8, 1], [0, 9], [5,-1], [8, 3]]

In [0]:
# type your code here
#use vertical split 

A = [[4, 7], [2, -3], [8, 1], [0, 9], [5,-1], [8, 3]]

In [138]:
type(A)

list

In [140]:
n = np.array(A)
n

array([[ 1,  4,  8],
       [ 5,  7,  3],
       [ 9, 14,  2]])

In [151]:
n1 = np.vsplit(n,3)

In [152]:
n1

[array([[8, 7, 0, 9]]), array([[ 2, -3,  5, 10]]), array([[ 8,  5, -1,  3]])]

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>17. Write a program to divide the array into two sub-arrays containing equal number of columns
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**

    B = [[8, 7, 0, 9], [2, -3, 5, 10], [8, 5, -1,3]]

In [145]:
# type your code here
#use horizontal split

B = [[8, 7, 0, 9], [2, -3, 5, 10], [8, 5, -1,3]]

n = np.array(B)
n

array([[ 8,  7,  0,  9],
       [ 2, -3,  5, 10],
       [ 8,  5, -1,  3]])

In [155]:
n1 = np.hsplit(n,2)

In [156]:
n1

[array([[ 8,  7],
        [ 2, -3],
        [ 8,  5]]),
 array([[ 0,  9],
        [ 5, 10],
        [-1,  3]])]

<a id="loop"> </a>
## 5. For Loop

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>18. Write a program to perform one-to-one mapping of the two lists</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the lists given below: (or create your own lists)**<br>

    L1 = [45, 67, 56, 71, 54, 62, 56]

    L2 = [21, 52, 64, 10, 49, 74, 26]

In [162]:
# type your code here


In [163]:
L1 = [45, 67, 56, 71, 54, 62, 56]

L2 = [21, 52, 64, 10, 49, 74, 26]


In [164]:


for i, j in zip(L1,L2):
    print(i,j)

45 21
67 52
56 64
71 10
54 49
62 74
56 26


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>19. Define a for loop to apply the function (2x-1)/(x+5) on every element of an array </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the list given below:**
    
    numbers = [6, 5, 3, 15]

In [166]:
# type your code here
#X
# no need to use for loop , just conv to nump array as it wont work without 'for loop' for lists 

x = [9,1,3,6,3,6]
a = np.array(x)
(2*a-1)/(a+5)

array([1.21428571, 0.16666667, 0.625     , 1.        , 0.625     ,
       1.        ])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>20. Create an identity matrix with n dimensions (take input from the user). Fill the diagonals of that matrix with the multiples of the number provided by the user; take another input from the user. Consider the output below as an example </b>
                </font>
            </div>
        </td>
    </tr>
</table>

<table align="center">
    <td height = '100', width = '700'>
          <img src="que 20.png">
        </td>
</table>

In [3]:
# type your code here
    
import numpy as np

x = int(input("Enter the number: "))
y = int(input("Enter the number to fill the diagonals with its multiples: "))
a = np.identity(x,)
b = np.fill_diagonal(a,y)
print(a)
print(b)

Enter the number: 4
Enter the number to fill the diagonals with its multiples: 6
[[6. 0. 0. 0.]
 [0. 6. 0. 0.]
 [0. 0. 6. 0.]
 [0. 0. 0. 6.]]
None
